version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/dvdrental
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: mysecretpassword
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"